function figure1=createhist(data1,name,colhist)
%CREATEFIGURE(data1)
%  DATA1:  histogram data

%  Auto-generated by MATLAB on 29-Sep-2021 16:21:11

% Create figure
figure1 = figure;
colormap(gray);

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create histogram
[n, xout]=hist(data1);
bar(xout, n, 'facecolor',colhist,'basevalue', 0.1);
set(gca,'YScale','log')
% Create ylabel
ylabel('Frequency (# of records)','FontWeight','bold');

% Create xlabel
xlabel(name,'FontWeight','bold');

box(axes1,'on');


hold(axes1,'off');




end
